### PR TITLE
Add () when instantiating the class to follow PER standard

### PR DESCRIPTION
**Pull request by s-patompong**
Add the `()` in the constructor call for consistency (and follow PHP standards too).

Reference to the standard: https://www.php-fig.org/per/coding-style/#4-classes-properties-and-methods.

### CODE REVIEW

**Comment by iainhallam** [comment]
Which PHP standards require this, @s-patompong? (I don't disagree that consistency is good, but would like to see the reference for choosing with brackets vs. without.)

**Comment by peter279k** [comment]
After looking at our codes in the repository, it has two different coding style about this:

For example, the line 214 in [src/HJSONParser.php](https://github.com/hjson/hjson-php/blob/master/src/HJSON/HJSONParser.php#L214) file and the line 158 in [tests/HJSONParserTest.php](https://github.com/hjson/hjson-php/blob/master/tests/HJSONParserTest.php#L158) file.

**Comment by s-patompong** [comment]
Hey man sorry just see this now @iainhallam.

I was referring to the PER standard https://www.php-fig.org/per/coding-style/#4-classes-properties-and-methods.

> When instantiating a new class, parentheses MUST always be present even when there are no arguments passed to the constructor.

I also value consistency in the codebase so I just want to help :)

**Review by trobro — APPROVED** [review]

**Review by peter279k — APPROVED** [review]

**Comment by peter279k** [comment]
I also suggest that we can consider adding the `phpcs.xml` to define the coding style since we add the `squizlabs/php_codesniffer` package in the `composer.json` `require-dev` block.

But I think the above recommendation is another PR.

**Pull request merged**
